package thyscom.taskeditor;

import java.util.HashMap;
import java.util.Map;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import thyscom.taskmodel.api.Task;

/**
 * Top component which displays the Task Editor.
 */
@ConvertAsProperties(dtd = "-//thyscom.taskeditor//TaskEditor//EN",
autostore = false)
@TopComponent.Description(preferredID = "TaskEditorTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "thyscom.taskeditor.TaskEditorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_TaskEditorAction",
preferredID = "TaskEditorTopComponent")
public final class TaskEditorTopComponent extends TopComponent {

    private static Map<Task, TaskEditorTopComponent> taskToEditorMap = new HashMap<Task, TaskEditorTopComponent>();

    /** 
     * Returns a TaskEditorTopComponent for the given task, if none exists
     * it is created.
     * @param task
     * @return 
     */
    public static TaskEditorTopComponent getInstance(Task task) {
        if (taskToEditorMap.containsKey(task)) {
            return taskToEditorMap.get(task);
        } else {
            return makeAndRegisterNewTopComponentForNewTask(task);
        }
    }

    private static TaskEditorTopComponent makeAndRegisterNewTopComponentForNewTask(Task task) {
        TaskEditorTopComponent tc = new TaskEditorTopComponent(task);
        taskToEditorMap.put(task, tc);
        return tc;
    }

    private TaskEditorTopComponent(Task task) {
        this();
        taskEditorPanel.setTask(task);
    }

    private TaskEditorTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(TaskEditorTopComponent.class, "CTL_TaskEditorTopComponent"));
        setToolTipText(NbBundle.getMessage(TaskEditorTopComponent.class, "HINT_TaskEditorTopComponent"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskEditorPanel = new thyscom.taskeditor.TaskEditorPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskEditorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskEditorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thyscom.taskeditor.TaskEditorPanel taskEditorPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
